### ISSUE TITLE
Compatibility with "RP Name in Quest Text" addon

### ISSUE THREAD

**Issue by NinerBull** [Peterodox/YUI-Dialogue#15]
Hey there,
I'm the author of [this addon](https://github.com/NinerBull/tRP3_RPNameInQuests) that uses the player's Total RP 3 profile and can replace the player's name/class/race in quest text, gossip text, books etc, with their chosen text.

I was looking to make it work with your new addon, I was able to get some success with the [changes I made in this commit](https://github.com/NinerBull/tRP3_RPNameInQuests/commit/7b1f93db4c93c2d0f6837da5474addb44fd15512), but that would also mean adding `##OptionalDeps: tRP3_RPNameInQuests` to DialogueUI's TOC.

I was wondering there would be a nicer way to do this though, my addon overwrites these functions which Dialogue UI uses local versions of:

- `C_GossipInfo.GetText`
- `GetGreetingText`
- `GetQuestText`
- `GetProgressText`
- `GetRewardText`
- `C_GossipInfo.GetOptions`

Thanks for reading!

**Comment by Peterodox** [comment]
Hi! [It's done](https://github.com/Peterodox/YUI-Dialogue/releases/tag/v0.2.4).
I utilized [TRP3_RPNameInQuests_CompleteRename](https://github.com/Peterodox/YUI-Dialogue/blob/v0.2.4/Code/SupportedAddOns/Roleplay.lua#L36) from your addon.

**Comment by NinerBull** [comment]
Much appreciated! Looks like it works, thank you very much!
