### ISSUE TITLE
Conflict with Interactive Wormholes

### ISSUE THREAD

**Issue by p3lim** [Peterodox/YUI-Dialogue#26]
Hey, this addon seems to be conflicting with my addon: https://github.com/p3lim-wow/InteractiveWormholes/issues/68

If you want to work together on a solution let me know. In essence my addon overrides the behavior when certain gossip options are present during `GOSSIP_SHOW`, just like yours, and I see no way of hooking into your addon to prevent it from colliding.

What I can do is expose an API in front of my database so you can stop processing if both my addon is loaded and this API returns true. I would in that case expose it as `InteractiveWormholes:IsActive()`, callable between `GOSSIP_SHOW` and `GOSSIP_CLOSED`, and you could use it like this:

```lua
if InteractiveWormholes and InteractiveWormholes:IsActive() then
  return
end
```

**Comment by Peterodox** [comment]
Hi! Thank you for providing the API. The two addons are compatible now 🥳
