### ISSUE TITLE
[Important Feature Request] Option to show original tooltips.

### ISSUE THREAD

**Issue by p0pcake** [Peterodox/YUI-Dialogue#28]
I currently have a lot of addons that enhance original tooltips and add huge amount of information to them.

The addon is truly great, but it shows its own tooltips and don't show information from any other addon like ATT or TSM :(

The simple option in settings to show original tooltips would let people like me choose what they want to see. 

If the quest window could also be movable in general, that'd be amazing.

**Comment by Peterodox** [comment]
I can add an option to use WoW's tooltip on our UI. But you will have to disable "Hide UI" in the settings.
- - -
You can switch the quest UI to the left or right of the screen, but it's difficult to move it freely. The camera's offset and the UI's position are linked together after some trial and error. And given the size of the window, there isn't much room to reposition it, right?

**Comment by p0pcake** [comment]
That sounds fair. The Hide UI option is great for immersion, but I’m assuming that everyone who just uses the addon for the convenience and general look turns that off anyway. These options if implemented would be a massive improvement :D

**Comment by Peterodox** [comment]
There is now an option named "Use Blizzard Tooltip" in Settings - UI. It's at the bottom of the list right now.
