### ISSUE TITLE
Game freeze when accepting quests

### ISSUE THREAD

**Issue by jaychez** [Peterodox/YUI-Dialogue#30]
Not all the time, just randomly freezes when accepting quests, have to restart game

**Comment by Peterodox** [comment]
If you google "Warcraft freeze quest" or "Warcraft crash quest" and filter the results by recent week, you will find some matches.

I didn't make any changes to quest accepting process, and I can't think of any reason on my end that could suddenly cause this after pre-patch. So I'm afraid there is nothing I can do to help at this moment.

**Comment by jaychez** [comment]
Sorry, my bad. Thank you for clarifying it.
