### ISSUE TITLE
Stops working after teleporting via Interactive Wormholes

### ISSUE THREAD

**Issue by filliph** [Peterodox/YUI-Dialogue#31]
First of all, many thanks for the compatibility fix for Interactive Wormholes (https://github.com/Peterodox/YUI-Dialogue/issues/26) 😄 

However, unfortunately Dialogue UI completely breaks after teleporting via Interactive Wormholes once. The next time you try to talk to any NPC, the original Blizzard dialogue box will flash, then the Dialogue UI box will flash, and then both boxes will close.

Is there any way you can take another look at the compatibility fix?

Thank you in advance 🙂

**Comment by Peterodox** [comment]
Hi! It should be functioning correctly now, thanks to p3lim, the dev of Interactive Wormholes.
