### ISSUE TITLE
[bug] Quest followup doesn't clear reward preview & prevents accepting follow-up quest

### ISSUE THREAD

**Issue by archonitex** [Peterodox/YUI-Dialogue#38]
## Describe the bug
This is noticed with using controller for gameplay, have not confirmed if it is the same with M&K.

When turning in a quest that has multiple rewards that are previewable, if the quest has a follow-up quest with the same NPC, the reward preview window does not close. It also prevents accepting the followup quest, and you are forced to walk away from the NPC and re-talk to them, at which point you can accept the quest normally.

## To Reproduce
1. Enable gamepad mode
2. Complete a quest that has multiple previewable rewards. This quest must have a follow-up quest with the same NPC.
3. "Hover" over each preview item. Select one. Complete quest. Observe the preview window not go away.
4. Observe follow-up quest cannot be accepted.

## Expected behavior
1. The reward preview window should close when completing the quest, not when the associated window closes (since there is a followup quest).

## Screenshots/Video
Video of follow-up quest issues: 
https://youtu.be/H8THe91NP_4 
(this highlights both the reward window not closing and the issue of not being able to accept followup);

Video of normal behavior with no followup quest (no issues here): 
https://youtu.be/nLyoaivbcN8

**Comment by MechaZao** [comment]
This occurs for me in normal keyboard operation as well since todays update.

**Comment by Peterodox** [comment]
Hi! Thanks for the video. I believe these two issues have the same cause (https://github.com/Peterodox/YUI-Dialogue/issues/36#issuecomment-2303563064)
Try the latest version v0.4.1 😃

**Comment by archonitex** [comment]
Hi @Peterodox this was recorded yesterday after having it updated to 0.4.1

**Comment by Peterodox** [comment]
I encountered the same issue twice in the last 4 hours of leveling. I'm not sure what caused it at this moment, but I'm now playing with both the default Quest Frame and our UI open. But before I can fix it, try clicking Exit/Goodbye and see if you can speak with the NPC again without leaving the interactable distance.

**Comment by archonitex** [comment]
At least on my end, it really only ever occurs when there's a follow-up quest from the same NPC. I have not seen occur ever when there is not followups.

**Comment by archonitex** [comment]
@Peterodox This seems to have resolved with one of the latest update. I don't experience the issue anymore. Thank you, and thanks for an amazing addon
