### ISSUE TITLE
Hide quest objective particle effect when UI is hidden ✨

### ISSUE THREAD

**Issue by robbirddotnet** [Peterodox/YUI-Dialogue#42]
When UI > Hide UI is enabled quest related NPCs begin to sparkle. This happens when hiding the UI, including using ALT-Z.

I haven't yet been able to replicate it, but clicking off an NPC too many times resulted in the effect being present while UI is visible. I believe this is an issue with Blizzard's code not handling an unusual situation.

![questj](https://github.com/user-attachments/assets/fead9551-7906-4c74-b94d-a5c4f14faaa4)

**Comment by Peterodox** [comment]
Unfortunately, it's just how this game behaves.
