### ISSUE TITLE
[Suggestion] DropDown list scrolling

### ISSUE THREAD

**Issue by BelegCufea** [Peterodox/YUI-Dialogue#45]
Hello Peterodox,

First of all, I want to say that I absolutely love your addon(s). What a treat!

I have a small issue with the dropdown menu. Since I’ve installed over 40 voices via the [Natrual  Voice SAPI Adapter](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter), the list in the dropdown is too long to fit on my 1080p monitor. I haven’t been able to figure out how to scroll through it (though I may just be missing something).

![image](https://github.com/user-attachments/assets/a30df1e0-a48b-4244-9978-a939d4f6009c)

It's a minor issue, as I can manually input the voiceID numbers into the saved variables file. I just wanted to bring it to your attention in case others run into the same problem.

Don’t worry about it too much—I'm sure there are more pressing matters to attend to.

Have a nice day!

**Comment by Peterodox** [comment]
Hi! Thank you.
I fear this may happen 😂
The drop-down memu was made in a rush so it doesn't have the ability to scroll up/down.
For now, you can switch the Input Device in Control to Xbox, which will transform the drop-down menu into a widget with two arrows (like the one we use for Speech Volume)

**Comment by BelegCufea** [comment]
@Peterodox No worries! As I mentioned, I’m fine with modifying the values directly in the saved variables file. I just wanted to let you know in case anyone else reports it. :-)
