### ISSUE TITLE
Character off center when transitioning into to cinematic from quest log

### ISSUE THREAD

**Issue by Areomayo** [Peterodox/YUI-Dialogue#48]
When i have the quest log open, and i start the cinematic from the quest log my character will be pushed to the left side of my screen so its no longer in the center.

auto zoom in is disabled, i have to /reload before my character is centered again.

I'm using ultra wide screen 34" maybe thats the reason for this weird bug?

![image](https://github.com/user-attachments/assets/47601680-3caa-4165-99a9-282ce818b22b)

**Comment by FlesHBoX** [comment]
Came here to report this behavior.  I have been experiencing it (also on a druid, and so far only on my druid).

From what I've been able to reproduce, it seems to happen if I reflexively hit 1 when entering a dialog, but the npc has no options other than escape (see screenshot), but this is not the only time I've seen this happen.  I likewise have seen it happen when exiting cinematics, as well as in a vehicle.
![WoWScrnShot_082824_195902](https://github.com/user-attachments/assets/cefbde54-3185-4816-90a7-7d153a03d94f)

**Comment by Areomayo** [comment]
my friend who recommended this addon to me does not have any problems, but he is running on a normal 27" monitor, so it could very well be a widescreen issue?

**Comment by Peterodox** [comment]
This issue is related to druid shapeshift. It's been fixed in [v0.4.5](https://legacy.curseforge.com/wow/addons/dialogueui/files/5676983)
