### ISSUE TITLE
Otoye - Battle for Dazar'alor

### ISSUE THREAD

**Issue by code-XmR** [Peterodox/YUI-Dialogue#51]
Talking to Otoye in Battle for Dazar'alor doesn't display a dialogue option to get to the final boss.

**Comment by Peterodox** [comment]
Hi!
Please enable "Use WoW's Default UI In Instance" in this addon's settings - Gameplay. It's at the bottom of the list.
The issue is likely a result of unintended interactions between different addons.

**Comment by zaranon** [comment]
Thank you, I somehow missed this setting. It's good enough for my purposes.
