### ISSUE TITLE
I can't find freshly installed narrator voices

### ISSUE THREAD

**Issue by C0wnuts** [Peterodox/YUI-Dialogue#54]
Hello,

I've just installed some new narrator voices (especially natural voices) and I can't find them in the selection list.
I've tried rerun the game, reinstalling the addon, restarting the PC, nothing fix the problem.

I'm running Windows 11 23H2
I'm in Qwerty layout with French language.

![Screenshot 2024-09-08 151019](https://github.com/user-attachments/assets/5f23bac1-fbe7-4a21-92f7-bcf9f1c383bd)

**Comment by BelegCufea** [comment]
@C0wnuts did you installed https://github.com/gexgd0419/NaturalVoiceSAPIAdapter as WoW only supports old Windows voices.

**Comment by Peterodox** [comment]
Hi! You'll have to install a program (mentioned in the link above)

**Comment by C0wnuts** [comment]
Thank you, it fixed it :)
