### ISSUE TITLE
[Accessibility Feature] Bigger Font

### ISSUE THREAD

**Issue by toktoktheeo** [Peterodox/YUI-Dialogue#58]
Hi,

I have a very poor eyesight and the max font size of 16 is too small for me.

Would it be possible to add bigger font sizes ? Something between 18 and 24 ?

Or would it be possible to point me to the right part of the code so I could increase the font size myself ?

Thanks for reading me,

**Comment by Peterodox** [comment]
Hi!
Try Settings - Control - Mobile Device Mode.

**Comment by toktoktheeo** [comment]
Thank you very much.

That's exactly what I was looking for.
