### ISSUE TITLE
[Bug report] Navigation Icons in German Language

### ISSUE THREAD

**Issue by SirSebi** [Peterodox/YUI-Dialogue#59]
if you play the game in english then there are the correkt navigation icons next to the text. In german, there are no icons according to the text.

![Screenshot 2024-09-14 223531](https://github.com/user-attachments/assets/aef9db54-f137-4539-b9c0-523349a8fd35)
![Screenshot 2024-09-14 223700](https://github.com/user-attachments/assets/1e195d35-c52a-4722-b716-10bfd94e9761)

**Comment by Peterodox** [comment]
It's been fixed in our latest update :)
