### ISSUE TITLE
[Suggestion] Warband completion

### ISSUE THREAD

**Issue by ddy987** [Peterodox/YUI-Dialogue#65]
It would be nice if there was text that indicated that the quest was completed by someone in your warband (like the default blizzard UI).

**Comment by BelegCufea** [comment]
This feature was already implemented in [v0.3.7](https://github.com/Peterodox/YUI-Dialogue/releases/tag/v0.3.7) (the checkmark after the questname)

![Warband](https://private-user-images.githubusercontent.com/49627468/356296085-c5f31bfe-5219-465a-ab07-c01f83a8be20.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODIwNDksIm5iZiI6MTcyODg4MTc0OSwicGF0aCI6Ii80OTYyNzQ2OC8zNTYyOTYwODUtYzVmMzFiZmUtNTIxOS00NjVhLWFiMDctYzAxZjgzYThiZTIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA0NTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OGM3MTQxZmJhYTRlMWY5MDExN2I2YmRlMTc4NWMzMWI4YTQ5MWE1YTcxZjgxNzkxZTA1NzkwOTVlOWI0ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gbzhSfjn4zSNQCp04cku9bsme3ihfOcn-D05VSuhCxQ)

**Comment by Peterodox** [comment]
The check mark on the right of the quest title indicates it's a Warband completed quest.
