### ISSUE TITLE
[Feedback | Question] TTS option in Quest

### ISSUE THREAD

**Issue by mapleleaf202324** [Peterodox/YUI-Dialogue#66]
Hello, I have a question: 

I play on the German client and love the possibility of using the TTS option for long quest texts. The German voices are very unpleasant, however. It doesn't matter whether they are male or female. There are now better versions of the TTS languages ​​and expressions. So by expressions I mean how the voice reads something out loud. Is there anything planned for the future? Or is work on the TTS options no longer being carried out?

Greetings

PS: Thanks for the great addon!

**Comment by mapleleaf202324** [comment]
https://github.com/gexgd0419/NaturalVoiceSAPIAdapter

**Comment by Peterodox** [comment]
After installing this you should be able to select Microsoft Natural Voice in the addon settings.
