### ISSUE TITLE
Dragon Soul NPC interaction failed to open addon UI

### ISSUE THREAD

**Issue by bravetothebone** [Peterodox/YUI-Dialogue#67]
in Dragon Soul raid when interacting with npc "[Sky Captain Swayze](https://www.wowhead.com/npc=55870/sky-captain-swayze)" when starting the fight (before the start - that NPC UI is the start of the encounter*) the addon don't work and no UI shows - on disabling the addon all works fine.

**Comment by bravetothebone** [comment]
After defeating the boss "Warmaster Blackhorn" same NPC UI is the next step, so 2nd time it wont work.

**Comment by bravetothebone** [comment]
After last boss defeat -> Same issue as previous NPC when interacting with "Thrall" or the Aspects. No options in their UI, but there's text in it. Disabling addon fixes the issue.

p.s. It's not new bug it happens since i installed the addon half an year ago, but today was the day i decided to post a bug report.

**Comment by Peterodox** [comment]
I'm not experiencing this issue, but there could be some unintended interactions between different addons.
Regardless, I'll add an option to our Settings - Gameplay that disables Dialogue UI in instance.


https://github.com/user-attachments/assets/48e8bce4-7430-41d6-ad90-ab5494ac1fa3

**Comment by Peterodox** [comment]
Hi!
Please enable "Use WoW's Default UI In Instance" in our Settings - Gameplay. It's at the bottom of the list.
