### ISSUE TITLE
[SoD] DialogueUI Auto-closes with Flight Masters and Vendors with Quests

### ISSUE THREAD

**Issue by illutian** [Peterodox/YUI-Dialogue#68]
Classic SoD:
For some reason with this addon enabled, when I talk a Flight Master and the Camera option is set to 'zoom in', the FM's dialogue (aka the flight path map) and DialogueUI open for an instant then closes and my Character Sheet is opened.

Same thing happens with Vendors that offer quests.

The only way around this is to hold SHIFT down before interacting with them, which still opens the Character Sheet. Or to disable the Camera 'zoom in'. But like with SHIFT, it still opens up the character sheet.

**Comment by Peterodox** [comment]
Hi!

The Shift key isn't used in this add-on to modify any NPC interaction. But it may be used by add-ons that provide quest auto turn-in or change flight map UI. And there are certainly no code in this add-on that open the character sheet.

I suspect this was caused by some unintended add-on interactions. I may be able to address it if you can narrow it down.

Alternatively, you can try disabling Hide UI in our add-on settings. (When interacting with an NPC, press F1 to open the settings)

**Comment by illutian** [comment]
> Hi!
> 
> The Shift key isn't used in this add-on to modify any NPC interaction. But it may be used by add-ons that provide quest auto turn-in or change flight map UI. And there are certainly no code in this add-on that open the character sheet.
> 
> I suspect this was caused by some unintended add-on interactions. I may be able to address it if you can narrow it down.
> 
> Alternatively, you can try disabling Hide UI in our add-on settings. (When interacting with an NPC, press F1 to open the settings)

Which would make it even more weird, because I use Leatrix Plus and do have 'auto quest turn in' active. But it's set to only 'auto turn in' when SHIFT is held down and the NPC is interacted with. So, by default quest turn-in works just like it would if I was using 'no mods' WoW.

Update: Nope, disabled Leatrix and the Character Sheet still opens up, and I disabled Immersion (makes interaction similar to Retail); Character Sheet still opens...and disabled Narcissus; Sheet still opens....and WeakAuras....

....Found it. DejaClassicStats. Had everything, but DialogueUI disabled and went through enabling each of the main ones starting with Dominos since I did make keybind changes (F1 is my hearth, for example). No clue why DCS is thinking I want the Sheet open.

I suspect this is because when you click on DCS in the AddOns tab of the game's Setting menu the Character Sheet is opened; my guess so you see the changes being made since UI element interaction (ie opening the Character Sheet) is disabled when the Settings menu is open.

**Comment by Peterodox** [comment]
I just installed DCS. If I only enable DCS and press Alt+Z twice to hide/re-show the UI, DCS's window will open. Not sure why it behaves this way 😂 
Disabling **Hide UI** in our settings will "fix" this issue.
![20241021214925](https://github.com/user-attachments/assets/eab19b14-0284-4f78-9ea1-d2ff94297ecb)
