### ISSUE TITLE
[Enhancement] Tab key (configurable?) to cycle through rewards

### ISSUE THREAD

**Issue by Road-block** [Peterodox/YUI-Dialogue#70]
Would be nice if we could use a key to cycle through the reward options before hitting the confirm key for true mouse-free operation.

![image](https://github.com/user-attachments/assets/257cd302-c83d-4d7f-84d9-b7eca3e3a5f7)
This kind of dialog as an example is where I'd like a way to select reward with keyboard.

_Apologies if this is already implemented and I missed the option somewhere._

**Comment by Peterodox** [comment]
It will be implemented in the next update.

**Comment by Road-block** [comment]
Tested the 0.48(pre) version with the tab option, working great 🏆

**Comment by Peterodox** [comment]
You're welcome!
