### ISSUE TITLE
Problem with ConsolePort

### ISSUE THREAD

**Issue by shaman78** [Peterodox/YUI-Dialogue#77]
When using this add-on combined with Console port it is nearly impossible to interact with a Flight master. 
The Flight master window closes automatically.

**Comment by shaman78** [comment]
Same fix as #68

**Comment by Peterodox** [comment]
It works fine on my end so it's likely due to another addon.
But again, disabling "Hide UI" usually fixes stuff like this.

https://github.com/user-attachments/assets/f94424a6-7bca-4a48-9a51-f8b5a631dd2f
