### ISSUE TITLE
Chosen font type resets to default one after relogging

### ISSUE THREAD

**Issue by Arkewas** [Peterodox/YUI-Dialogue#80]
Hi Peter,
I set the font type as "Boris Black Bloxx" (Screenshot 1)  but after exiting WoW and relogging to it (not a simple UI reload or disconnect / reconnect) it resets to the default one, even if in the font's field it still shows "Boris Black Bloxx" (Screenshot 2)

[Edit] I just logged and tested it with 2 different characters from different realms. The issue occurred with both of them,  no LUA errors.

[Edit] Today I logged and all it's fine. It seems the issue occurs randomly so probably it's very difficult, if not impossible, to find the reason of it.

**(Screenshot 1)**

![Dialogue UI font type](https://github.com/user-attachments/assets/45693ddf-5570-41da-b8ea-27962e802166)

(Screenshot 2)

![Dialogue UI wrong font type](https://github.com/user-attachments/assets/848d260d-f35c-4ad2-8c71-23a1c9d79a90)

**Comment by Peterodox** [comment]
Hi!
It should be fixed in v0.5.1 😄

**Comment by Arkewas** [comment]
Thank you for releasing a fixed version, very fast as usual.
