### ISSUE TITLE
[Suggestion] Rematch integration

### ISSUE THREAD

**Issue by Alexandertp** [Peterodox/YUI-Dialogue#83]
I love the recent BTWQuests integration, and I do a lot of pet battling, so it would be awesome to either in some form integrate the Pet Team Selection Box with DialogueUI, or have it be in some way exempt from being hidden when interacting with a Pet Battling NPC.

**Comment by Peterodox** [comment]
We do support Rematch. The Rematch window should be visible when you interact with the NPC, at least on my end.
You need to change "On Target" in Rematch Options - Interaction Options to "Prompt to Load" or "Show Window".

![RematchWindow](https://github.com/user-attachments/assets/f210913d-daaf-47fe-99c7-6e7ad182c2a5)
