### ISSUE TITLE
[BUG] Encoded character behavior

### ISSUE THREAD

**Issue by KatyPurry** [Peterodox/YUI-Dialogue#86]
Hello,

There is a small encoding problem in French with a space with some objects, notably : [My Journal: Nola's Last Wish](https://www.wowhead.com/item=228302/my-journal-nolas-last-wish)

![image](https://github.com/user-attachments/assets/0afda0fb-6004-4aa6-8fa3-deab52389b4f)

**Comment by Peterodox** [comment]
Hi! It's been fixed in the latest update.
There is a no-break space before the colon and the title font I used doesn't have this character, only regular space.
