### ISSUE TITLE
no dialog popup in 2 raids

### ISSUE THREAD

**Issue by JarfJarfBinks** [Peterodox/YUI-Dialogue#88]
Antorus and Battle of Dazar'alor with elvui enabled, works when I disable elvui tho

**Comment by Peterodox** [comment]
Hi!
Please enable "Use WoW's Default UI In Instance" in our Settings - Gameplay. It's at the bottom of the list.

**Comment by Peterodox** [comment]
Hello! Were you using ElvUI WindTools when it happened?

**Comment by JarfJarfBinks** [comment]
> Hello! Were you using ElvUI WindTools when it happened?

yes I was
