### ISSUE TITLE
After talking to a NPC the Character page automatically opens

### ISSUE THREAD

**Issue by leanderjanssen** [Peterodox/YUI-Dialogue#90]
Since updating to version 0.5.3 for Classic each time I talk to a NPC the character screen opens automatically after close the dialog with the NPC. Is there a way to disable this behaviour? Or is this a bug?

**Comment by Peterodox** [comment]
I assume you're using DejaCharacterStats?

https://github.com/Peterodox/YUI-Dialogue/issues/68#issuecomment-2426744531

**Comment by leanderjanssen** [comment]
Yep, thanks for pointing this out. I'll close the issue.
