### ISSUE TITLE
Teleports

### ISSUE THREAD

**Issue by Hafler** [Peterodox/YUI-Dialogue#92]
I use a lot of teleports and it seems like this addon blocks their usage. Things like Reaves wormhole mode, or Grand Artificer Romuul on the Vindicar at the end of Antorus simply don't pop up unless i disable the addon.

**Comment by Peterodox** [comment]
Hi!
It may conflict with another addon because using Dialogue UI alone doesn't cause this issue.
Could you please try disabling other add-ons one by one until it starts working?

**Comment by Hafler** [comment]
Ah yeah, looks like dialogue key was the culprit.
