### ISSUE TITLE
BookUI Error with Libram Items

### ISSUE THREAD

**Issue by Haembina** [Peterodox/YUI-Dialogue#93]
Tested with:
**Libram of Rumination
Libram of Constitution
Libram of Resilience
Libram of Voracity
Libram of Tenacity**

Error from BugSack: 

1x DialogueUI/Code/Book/BookUI.lua:928: attempt to compare nil with number
[string "@DialogueUI/Code/Book/BookUI.lua"]:928: in function `GetCurrentPage'
[string "@DialogueUI/Code/Book/BookUI.lua"]:1357: in function `UpdatePagination'
[string "@DialogueUI/Code/Scroll/Scroll_EasySmooth.lua"]:151: in function `SnapTo'
[string "@DialogueUI/Code/Scroll/Scroll_EasySmooth.lua"]:156: in function `ResetScroll'
[string "@DialogueUI/Code/Book/BookUI.lua"]:840: in function `ResetScroll'
[string "@DialogueUI/Code/Book/BookUI.lua"]:1257: in function `RebuildContentFromCache'
[string "@DialogueUI/Code/Book/BookUI.lua"]:1487: in function `ShowUI'
[string "@DialogueUI/Code/Book/BookUI.lua"]:361: in function <DialogueUI/Code/Book/BookUI.lua:346>

Locals:
self = DUIBookFrame {
 nodeignore = true
 scrollFromOffetY = 15
 widgetTheme = 4
 textureFile = "DialogueUI/Art/Book/TextureKit-Metal.png"
 CloseButton = Button {
 }
 textureKitID = 2
 fontStringPool = <table> {
 }
 ContentFrame = Frame {
 }
 Header = Frame {
 }
 CopyTextButton = Button {
 }
 defaultOffsetX = -634.666667
 SourceItemButton = Frame {
 }
 useTwoPieceBG = true
 PixelSnapDisabled = true
 defaultAnchor = "LEFT"
 Footer = Frame {
 }
 ScrollFrame = ScrollFrame {
 }
 ScreenVignette = Texture {
 }
 texturePool = <table> {
 }
 scrollable = true
 BackgroundPieces = <table> {
 }
}
offset = 132.071143
maxPage = 4
pageOffset = nil
(for index) = 4
(for limit) = 1
(for step) = -1
page = 4
(*temporary) = nil
(*temporary) = Frame {
 t = 0
 needTurnBack = false
 data = <table> {
 }
 fromContentIndex = 8
 toContentIndex = 7
 nextContentIsPageStart = true
 fullyCached = true
 identifier = "Item11732"
 activeData = <table> {
 }
}
(*temporary) = 4
(*temporary) = "attempt to compare nil with number"
Cache = Frame {
 t = 0
 needTurnBack = false
 data = <table> {
 }
 fromContentIndex = 8
 toContentIndex = 7
 nextContentIsPageStart = true
 fullyCached = true
 identifier = "Item11732"
 activeData = <table> {
 }
}

**Comment by Peterodox** [comment]
Hi! Could you enable the Copy Text button in the addon Settings - UI, copy the raw text, and send it here? Any one of these books is fine.
I think something went wrong because these books have images and they may use a different syntax.

**Comment by Peterodox** [comment]
Thanks :)
I've located the issue. It will be fixed in the next update and the images will be correctly displayed.
