### ISSUE TITLE
Addon prevents talking to Jaina skip in mythic Battle of Dazar'alor

### ISSUE THREAD

**Issue by matthewmerendo** [Peterodox/YUI-Dialogue#95]
Basically what the title says -- if I have the add-on enabled, I cannot talk to the NPC that offers the skip straight to Jaina in Battle of Dazar'alor.

**Comment by Peterodox** [comment]
Hi!
Please enable "Use WoW's Default UI In Instance" in our Settings - Gameplay. It's at the bottom of the list.

**Comment by matthewmerendo** [comment]
Ah, brilliant! Thank you, and sorry for opening a ticket about a non-issue!
