### ISSUE TITLE
[feature request] less delay on TTS starting

### ISSUE THREAD

**Issue by SLinxTheFox** [Peterodox/YUI-Dialogue#96]
i switched over from quest TTS and immersion, i really like this addon, but there's often a .5 to 2 second delay on when the TTS starts.

if that can be fixed/changed i would greatly appreciate it. thank you for the addon regardless <3

**Comment by Peterodox** [comment]
There are 2 factors that affect the delay before TTS starts:
1. If you are using an online voice, there will be an unavoidable delay before the TTS service sends the response to your computer.
2. Check our add-on Settings to see if you have enabled "Delay Reading." This option is only visible when "Auto Play" is on.

**Comment by SLinxTheFox** [comment]
probably an online voice issue then as i'm using the natural voices. thank you for the response!
