### ISSUE TITLE
"Your Warband previously completed this quest." not shown

### ISSUE THREAD

**Issue by dzehme** [Peterodox/YUI-Dialogue#99]
![image](https://github.com/user-attachments/assets/997599fb-324e-4de3-8758-fac777b2f047)

If I have a quest that I have previously completed on another character, I don't see this message in this addon's UI but I do see it in the default UI.   This text is an important indicator as it usually controls if reputation will be rewarded for the completion of the quest.   Please update to display this text or an indicator for the text in your wonderful UI.

**Comment by Peterodox** [comment]
Hi!
The check mark on the right of the quest title indicates it's a Warband completed quest.

![356296085-c5f31bfe-5219-465a-ab07-c01f83a8be20.jpg](https://github.com/user-attachments/assets/1e3738dc-8507-4148-b3a5-c6341e1a3049)

**Comment by dzehme** [comment]
Thanks for that.   For some reason I had not noticed that.
